services:
  - type: static_site
    name: calificaciones-frontend
    rootDir: Frontend-calificacionesOnlineGBD/frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://gestor-calificaciones.onrender.com/api